"""
oui_db.py — Base OUI focada no parque SML Portugal.
Fabricantes: Dell, Lenovo, HP, OKI, Konica Minolta, Zebra, Brother,
             Cisco, HPE Aruba, Dell Networking, Ubiquiti, Asus
Sem duplicados — cada OUI tem exactamente um fabricante/tipo.
"""

OUI_DATABASE = {

    # ══════════ ASUSTeK Computer ══════════
    "00:1a:92": ("ASUSTeK Computer", "Desktop"),
    "00:1b:fc": ("ASUSTeK Computer", "Desktop"),
    "00:1d:60": ("ASUSTeK Computer", "Desktop"),
    "00:1e:8c": ("ASUSTeK Computer", "Desktop"),
    "00:1f:c6": ("ASUSTeK Computer", "Desktop"),
    "00:22:15": ("ASUSTeK Computer", "Desktop"),
    "00:23:54": ("ASUSTeK Computer", "Desktop"),
    "00:24:8c": ("ASUSTeK Computer", "Desktop"),
    "00:26:18": ("ASUSTeK Computer", "Desktop"),
    "04:92:26": ("ASUSTeK Computer", "Desktop"),
    "08:60:6e": ("ASUSTeK Computer", "Desktop"),
    "0c:9d:92": ("ASUSTeK Computer", "Desktop"),
    "10:02:b5": ("ASUSTeK Computer", "Desktop"),
    "10:bf:48": ("ASUSTeK Computer", "Desktop"),
    "14:da:e9": ("ASUSTeK Computer", "Desktop"),
    "18:31:bf": ("ASUSTeK Computer", "Desktop"),
    "1c:87:2c": ("ASUSTeK Computer", "Desktop"),
    "20:cf:30": ("ASUSTeK Computer", "Desktop"),
    "2c:56:dc": ("ASUSTeK Computer", "Desktop"),
    "2c:fd:a1": ("ASUSTeK Computer", "Desktop"),
    "30:85:a9": ("ASUSTeK Computer", "Desktop"),
    "34:97:f6": ("ASUSTeK Computer", "Desktop"),
    "38:d5:47": ("ASUSTeK Computer", "Desktop"),
    "3c:7c:3f": ("ASUSTeK Computer", "Desktop"),
    "40:16:7e": ("ASUSTeK Computer", "Desktop"),
    "40:b0:76": ("ASUSTeK Computer", "Desktop"),
    "4c:ed:fb": ("ASUSTeK Computer", "Desktop"),
    "50:46:5d": ("ASUSTeK Computer", "Desktop"),
    "54:04:a6": ("ASUSTeK Computer", "Desktop"),
    "54:a0:50": ("ASUSTeK Computer", "Desktop"),
    "58:11:22": ("ASUSTeK Computer", "Desktop"),
    "5c:ff:35": ("ASUSTeK Computer", "Desktop"),
    "60:45:cb": ("ASUSTeK Computer", "Desktop"),
    "6c:62:6d": ("ASUSTeK Computer", "Desktop"),
    "70:4d:7b": ("ASUSTeK Computer", "Desktop"),
    "74:d0:2b": ("ASUSTeK Computer", "Desktop"),
    "78:24:af": ("ASUSTeK Computer", "Desktop"),
    "7c:67:a2": ("ASUSTeK Computer", "Desktop"),
    "80:65:f9": ("ASUSTeK Computer", "Desktop"),
    "84:a9:38": ("ASUSTeK Computer", "Desktop"),
    "88:d7:f6": ("ASUSTeK Computer", "Desktop"),
    "8c:89:a5": ("ASUSTeK Computer", "Desktop"),
    "90:e6:ba": ("ASUSTeK Computer", "Desktop"),
    "94:de:80": ("ASUSTeK Computer", "Desktop"),
    "98:3b:8f": ("ASUSTeK Computer", "Desktop"),
    "9c:5c:8e": ("ASUSTeK Computer", "Desktop"),
    "a0:8c:fd": ("ASUSTeK Computer", "Desktop"),
    "a8:5e:45": ("ASUSTeK Computer", "Desktop"),
    "ac:22:0b": ("ASUSTeK Computer", "Desktop"),
    "b0:6e:bf": ("ASUSTeK Computer", "Desktop"),
    "b4:2e:99": ("ASUSTeK Computer", "Desktop"),
    "bc:ae:c5": ("ASUSTeK Computer", "Desktop"),
    "c0:3f:d5": ("ASUSTeK Computer", "Desktop"),
    "c4:04:15": ("ASUSTeK Computer", "Desktop"),
    "c8:60:00": ("ASUSTeK Computer", "Desktop"),
    "cc:3d:82": ("ASUSTeK Computer", "Desktop"),
    "d0:17:c2": ("ASUSTeK Computer", "Desktop"),
    "d4:5d:df": ("ASUSTeK Computer", "Desktop"),
    "d8:50:e6": ("ASUSTeK Computer", "Desktop"),
    "dc:fe:07": ("ASUSTeK Computer", "Desktop"),
    "e0:3f:49": ("ASUSTeK Computer", "Desktop"),
    "e4:b9:7a": ("ASUSTeK Computer", "Desktop"),
    "e8:9c:25": ("ASUSTeK Computer", "Desktop"),
    "ec:4c:4d": ("ASUSTeK Computer", "Desktop"),
    "f4:6d:04": ("ASUSTeK Computer", "Desktop"),
    "f8:32:e4": ("ASUSTeK Computer", "Desktop"),
    "fc:aa:14": ("ASUSTeK Computer", "Desktop"),

    # ══════════ Brother Industries ══════════
    "00:1b:a9": ("Brother Industries", "Impressora"),
    "04:02:1f": ("Brother Industries", "Impressora"),
    "0c:49:4e": ("Brother Industries", "Impressora"),
    "10:9a:dd": ("Brother Industries", "Impressora"),
    "14:2d:27": ("Brother Industries", "Impressora"),
    "1c:c0:e1": ("Brother Industries", "Impressora"),
    "20:c3:e9": ("Brother Industries", "Impressora"),
    "28:98:8b": ("Brother Industries", "Impressora"),
    "2c:23:3a": ("Brother Industries", "Impressora"),
    "30:05:5c": ("Brother Industries", "Impressora"),
    "34:12:98": ("Brother Industries", "Impressora"),
    "38:50:64": ("Brother Industries", "Impressora"),
    "3c:e0:72": ("Brother Industries", "Impressora"),
    "44:5e:f3": ("Brother Industries", "Impressora"),
    "4c:c1:5e": ("Brother Industries", "Impressora"),
    "58:46:9c": ("Brother Industries", "Impressora"),
    "60:f1:89": ("Brother Industries", "Impressora"),
    "64:f0:69": ("Brother Industries", "Impressora"),
    "68:f0:76": ("Brother Industries", "Impressora"),
    "6c:e8:c6": ("Brother Industries", "Impressora"),
    "70:77:81": ("Brother Industries", "Impressora"),
    "74:27:ea": ("Brother Industries", "Impressora"),
    "74:e2:f5": ("Brother Industries", "Impressora"),
    "78:ba:f9": ("Brother Industries", "Impressora"),
    "7c:57:3c": ("Brother Industries", "Impressora"),
    "80:f6:2e": ("Brother Industries", "Impressora"),
    "84:ef:18": ("Brother Industries", "Impressora"),
    "8c:7a:aa": ("Brother Industries", "Impressora"),
    "90:f6:52": ("Brother Industries", "Impressora"),
    "94:4a:0f": ("Brother Industries", "Impressora"),
    "98:8d:46": ("Brother Industries", "Impressora"),
    "9c:a5:25": ("Brother Industries", "Impressora"),
    "a0:75:b5": ("Brother Industries", "Impressora"),
    "a8:54:b2": ("Brother Industries", "Impressora"),
    "ac:67:06": ("Brother Industries", "Impressora"),
    "ac:7f:3e": ("Brother Industries", "Impressora"),
    "b0:7c:59": ("Brother Industries", "Impressora"),
    "b8:08:be": ("Brother Industries", "Impressora"),
    "bc:5c:4c": ("Brother Industries", "Impressora"),
    "c0:96:97": ("Brother Industries", "Impressora"),
    "c4:00:ad": ("Brother Industries", "Impressora"),
    "c8:b3:73": ("Brother Industries", "Impressora"),
    "cc:fb:65": ("Brother Industries", "Impressora"),
    "d4:63:fe": ("Brother Industries", "Impressora"),
    "d8:40:c4": ("Brother Industries", "Impressora"),
    "dc:2c:26": ("Brother Industries", "Impressora"),
    "e0:06:e6": ("Brother Industries", "Impressora"),
    "e4:98:d6": ("Brother Industries", "Impressora"),
    "e8:2a:ea": ("Brother Industries", "Impressora"),
    "ec:1d:72": ("Brother Industries", "Impressora"),
    "f0:de:f1": ("Brother Industries", "Impressora"),
    "f4:3e:61": ("Brother Industries", "Impressora"),
    "f8:0f:f9": ("Brother Industries", "Impressora"),
    "fc:58:fa": ("Brother Industries", "Impressora"),

    # ══════════ Cisco Systems ══════════
    "00:00:0c": ("Cisco Systems", "Switch"),
    "00:01:42": ("Cisco Systems", "Switch"),
    "00:01:63": ("Cisco Systems", "Switch"),
    "00:01:96": ("Cisco Systems", "Switch"),
    "00:01:c7": ("Cisco Systems", "Switch"),
    "00:02:16": ("Cisco Systems", "Switch"),
    "00:03:6b": ("Cisco Systems", "Switch"),
    "00:04:9a": ("Cisco Systems", "Switch"),
    "00:05:9a": ("Cisco Systems", "Switch"),
    "00:06:28": ("Cisco Systems", "Switch"),
    "00:07:0d": ("Cisco Systems", "Switch"),
    "00:08:20": ("Cisco Systems", "Switch"),
    "00:09:11": ("Cisco Systems", "Switch"),
    "00:0a:41": ("Cisco Systems", "Switch"),
    "00:0a:8a": ("Cisco Systems", "Switch"),
    "00:0b:45": ("Cisco Systems", "Switch"),
    "00:0b:fc": ("Cisco Systems", "Switch"),
    "00:0c:30": ("Cisco Systems", "Switch"),
    "00:0c:85": ("Cisco Systems", "Switch"),
    "00:0d:28": ("Cisco Systems", "Switch"),
    "00:0d:bc": ("Cisco Systems", "Switch"),
    "00:0e:38": ("Cisco Systems", "Switch"),
    "00:0e:83": ("Cisco Systems", "Switch"),
    "00:0e:d7": ("Cisco Systems", "Switch"),
    "00:0f:23": ("Cisco Systems", "Switch"),
    "00:0f:8f": ("Cisco Systems", "Switch"),
    "00:0f:f7": ("Cisco Systems", "Switch"),
    "00:10:07": ("Cisco Systems", "Switch"),
    "00:10:79": ("Cisco Systems", "Switch"),
    "00:10:f6": ("Cisco Systems", "Switch"),
    "00:11:20": ("Cisco Systems", "Switch"),
    "00:11:bb": ("Cisco Systems", "Switch"),
    "00:12:01": ("Cisco Systems", "Switch"),
    "00:12:43": ("Cisco Systems", "Switch"),
    "00:12:7f": ("Cisco Systems", "Switch"),
    "00:12:d9": ("Cisco Systems", "Switch"),
    "00:13:19": ("Cisco Systems", "Switch"),
    "00:13:5f": ("Cisco Systems", "Switch"),
    "00:13:c3": ("Cisco Systems", "Switch"),
    "00:14:1b": ("Cisco Systems", "Switch"),
    "00:14:69": ("Cisco Systems", "Switch"),
    "00:14:bf": ("Cisco Systems", "Switch"),
    "00:15:2b": ("Cisco Systems", "Switch"),
    "00:15:63": ("Cisco Systems", "Switch"),
    "00:15:c6": ("Cisco Systems", "Switch"),
    "00:16:46": ("Cisco Systems", "Switch"),
    "00:16:9c": ("Cisco Systems", "Switch"),
    "00:16:c7": ("Cisco Systems", "Switch"),
    "00:17:0e": ("Cisco Systems", "Switch"),
    "00:17:59": ("Cisco Systems", "Switch"),
    "00:17:94": ("Cisco Systems", "Switch"),
    "00:17:df": ("Cisco Systems", "Switch"),
    "00:18:18": ("Cisco Systems", "Switch"),
    "00:18:73": ("Cisco Systems", "Switch"),
    "00:18:b9": ("Cisco Systems", "Switch"),
    "00:19:06": ("Cisco Systems", "Switch"),
    "00:19:55": ("Cisco Systems", "Switch"),
    "00:19:aa": ("Cisco Systems", "Switch"),
    "00:1a:2f": ("Cisco Systems", "Switch"),
    "00:1a:6c": ("Cisco Systems", "Switch"),
    "00:1a:8c": ("Cisco Systems", "Switch"),
    "00:1a:a1": ("Cisco Systems", "Switch"),
    "00:1b:2a": ("Cisco Systems", "Switch"),
    "00:1b:53": ("Cisco Systems", "Switch"),
    "00:1b:8f": ("Cisco Systems", "Switch"),
    "00:1b:d4": ("Cisco Systems", "Switch"),
    "00:1c:10": ("Cisco Systems", "Switch"),
    "00:1c:57": ("Cisco Systems", "Switch"),
    "00:1c:b0": ("Cisco Systems", "Switch"),
    "00:1c:f6": ("Cisco Systems", "Switch"),
    "00:1d:45": ("Cisco Systems", "Switch"),
    "00:1d:70": ("Cisco Systems", "Switch"),
    "00:1d:a1": ("Cisco Systems", "Switch"),
    "00:1d:e5": ("Cisco Systems", "Switch"),
    "00:1e:13": ("Cisco Systems", "Switch"),
    "00:1e:49": ("Cisco Systems", "Switch"),
    "00:1e:7a": ("Cisco Systems", "Switch"),
    "00:1e:be": ("Cisco Systems", "Switch"),
    "00:1f:26": ("Cisco Systems", "Switch"),
    "00:1f:6c": ("Cisco Systems", "Switch"),
    "00:1f:9e": ("Cisco Systems", "Switch"),
    "00:21:1b": ("Cisco Systems", "Switch"),
    "00:21:55": ("Cisco Systems", "Switch"),
    "00:21:a0": ("Cisco Systems", "Switch"),
    "00:22:0c": ("Cisco Systems", "Switch"),
    "00:22:55": ("Cisco Systems", "Switch"),
    "00:22:90": ("Cisco Systems", "Switch"),
    "00:22:bd": ("Cisco Systems", "Switch"),
    "00:23:33": ("Cisco Systems", "Switch"),
    "00:23:5e": ("Cisco Systems", "Switch"),
    "00:23:ac": ("Cisco Systems", "Switch"),
    "00:23:ae": ("Cisco Systems", "Switch"),
    "00:23:ea": ("Cisco Systems", "Switch"),
    "00:24:13": ("Cisco Systems", "Switch"),
    "00:24:50": ("Cisco Systems", "Switch"),
    "00:24:97": ("Cisco Systems", "Switch"),
    "00:24:c3": ("Cisco Systems", "Switch"),
    "00:25:45": ("Cisco Systems", "Switch"),
    "00:25:84": ("Cisco Systems", "Switch"),
    "00:25:b4": ("Cisco Systems", "Switch"),
    "00:26:0a": ("Cisco Systems", "Switch"),
    "00:26:51": ("Cisco Systems", "Switch"),
    "00:26:98": ("Cisco Systems", "Switch"),
    "00:26:cb": ("Cisco Systems", "Switch"),
    "00:27:0d": ("Cisco Systems", "Switch"),
    "2c:54:2d": ("Cisco Systems", "Switch"),
    "3c:0e:23": ("Cisco Systems", "Switch"),
    "54:78:1a": ("Cisco Systems", "Switch"),
    "58:97:bd": ("Cisco Systems", "Switch"),
    "70:0f:6a": ("Cisco Systems", "Switch"),
    "84:b8:02": ("Cisco Systems", "Switch"),
    "9c:57:ad": ("Cisco Systems", "Switch"),
    "a4:4c:11": ("Cisco Systems", "Switch"),
    "b0:aa:77": ("Cisco Systems", "Switch"),
    "c4:71:fe": ("Cisco Systems", "Switch"),
    "c8:00:84": ("Cisco Systems", "Switch"),
    "d0:c2:82": ("Cisco Systems", "Switch"),
    "e8:ba:70": ("Cisco Systems", "Switch"),
    "f4:0f:1b": ("Cisco Systems", "Switch"),
    "f8:7b:20": ("Cisco Systems", "Switch"),

    # ══════════ Dell Inc. ══════════
    "00:06:5b": ("Dell Inc.", "Desktop"),
    "00:08:74": ("Dell Inc.", "Desktop"),
    "00:0b:db": ("Dell Inc.", "Desktop"),
    "00:0d:56": ("Dell Inc.", "Desktop"),
    "00:0f:1f": ("Dell Inc.", "Desktop"),
    "00:10:18": ("Dell Inc.", "Desktop"),
    "00:11:43": ("Dell Inc.", "Desktop"),
    "00:12:3f": ("Dell Inc.", "Desktop"),
    "00:13:72": ("Dell Inc.", "Desktop"),
    "00:14:22": ("Dell Inc.", "Desktop"),
    "00:15:c5": ("Dell Inc.", "Desktop"),
    "00:16:f0": ("Dell Inc.", "Desktop"),
    "00:18:8b": ("Dell Inc.", "Desktop"),
    "00:19:b9": ("Dell Inc.", "Desktop"),
    "00:1a:11": ("Dell Inc.", "Desktop"),
    "00:1c:23": ("Dell Inc.", "Desktop"),
    "00:1d:09": ("Dell Inc.", "Desktop"),
    "00:1e:4f": ("Dell Inc.", "Desktop"),
    "00:1f:d0": ("Dell Inc.", "Desktop"),
    "00:21:70": ("Dell Inc.", "Desktop"),
    "00:22:19": ("Dell Inc.", "Desktop"),
    "00:24:e8": ("Dell Inc.", "Desktop"),
    "00:25:64": ("Dell Inc.", "Desktop"),
    "00:26:b9": ("Dell Inc.", "Desktop"),
    "00:60:48": ("Dell Inc.", "Desktop"),
    "00:b0:d0": ("Dell Inc.", "Desktop"),
    "14:18:77": ("Dell Inc.", "Servidor"),
    "18:03:73": ("Dell Inc.", "Servidor"),
    "34:17:eb": ("Dell Inc.", "Desktop"),
    "44:a8:42": ("Dell Inc.", "Desktop"),
    "68:4f:64": ("Dell Inc.", "Desktop"),
    "8c:04:ba": ("Dell Inc.", "Servidor"),
    "a4:bb:6d": ("Dell Inc.", "Desktop"),
    "b0:83:fe": ("Dell Inc.", "Desktop"),
    "b8:ca:3a": ("Dell Inc.", "Desktop"),
    "c8:1f:66": ("Dell Inc.", "Desktop"),
    "d4:81:d7": ("Dell Inc.", "Desktop"),
    "d8:9e:f3": ("Dell Inc.", "Desktop"),
    "ec:f4:bb": ("Dell Inc.", "Desktop"),
    "f0:4d:a2": ("Dell Inc.", "Desktop"),
    "f4:8e:38": ("Dell Inc.", "Desktop"),
    "f8:db:88": ("Dell Inc.", "Desktop"),

    # ══════════ Dell Networking ══════════
    "00:00:e8": ("Dell Networking", "Switch"),
    "00:01:e8": ("Dell Networking", "Switch"),
    "34:04:9e": ("Dell Networking", "Switch"),
    "54:9f:35": ("Dell Networking", "Switch"),
    "64:00:6a": ("Dell Networking", "Switch"),
    "84:8f:69": ("Dell Networking", "Switch"),
    "a0:d3:c1": ("Dell Networking", "Switch"),
    "d0:67:e5": ("Dell Networking", "Switch"),
    "f8:b1:56": ("Dell Networking", "Switch"),

    # ══════════ HP Inc. ══════════
    "00:17:08": ("HP Inc.", "Impressora"),
    "00:1b:78": ("HP Inc.", "Impressora"),
    "00:80:77": ("HP Inc.", "Impressora"),
    "18:a9:05": ("HP Inc.", "Impressora"),
    "1c:c1:de": ("HP Inc.", "Impressora"),
    "28:92:4a": ("HP Inc.", "Impressora"),
    "2c:27:d7": ("HP Inc.", "Impressora"),
    "38:63:bb": ("HP Inc.", "Impressora"),
    "38:ea:a7": ("HP Inc.", "Impressora"),
    "40:b0:34": ("HP Inc.", "Impressora"),
    "48:07:2e": ("HP Inc.", "Impressora"),
    "4c:39:09": ("HP Inc.", "Impressora"),
    "64:51:06": ("HP Inc.", "Impressora"),
    "70:5a:0f": ("HP Inc.", "Impressora"),
    "70:e8:51": ("HP Inc.", "Impressora"),
    "78:48:59": ("HP Inc.", "Impressora"),
    "78:ac:c0": ("HP Inc.", "Impressora"),
    "80:ce:62": ("HP Inc.", "Impressora"),
    "8c:dc:d4": ("HP Inc.", "Impressora"),
    "90:e7:c4": ("HP Inc.", "Impressora"),
    "94:57:a5": ("HP Inc.", "Impressora"),
    "98:e7:f4": ("HP Inc.", "Impressora"),
    "9c:b6:54": ("HP Inc.", "Impressora"),
    "a0:b3:cc": ("HP Inc.", "Impressora"),
    "b4:99:ba": ("HP Inc.", "Impressora"),
    "b4:b5:2f": ("HP Inc.", "Impressora"),
    "bc:ea:fa": ("HP Inc.", "Impressora"),
    "c4:34:6b": ("HP Inc.", "Impressora"),
    "d8:3a:dd": ("HP Inc.", "Impressora"),
    "d8:d3:85": ("HP Inc.", "Impressora"),
    "e8:39:35": ("HP Inc.", "Impressora"),
    "f4:ce:46": ("HP Inc.", "Impressora"),
    "fc:15:b4": ("HP Inc.", "Impressora"),

    # ══════════ HPE Aruba ══════════
    "00:0b:86": ("HPE Aruba", "Access Point"),
    "00:1a:1e": ("HPE Aruba", "Access Point"),
    "00:24:6c": ("HPE Aruba", "Access Point"),
    "04:bd:88": ("HPE Aruba", "Access Point"),
    "08:ea:44": ("HPE Aruba", "Access Point"),
    "10:05:ca": ("HPE Aruba", "Access Point"),
    "18:64:72": ("HPE Aruba", "Access Point"),
    "20:4c:03": ("HPE Aruba", "Access Point"),
    "24:79:2a": ("HPE Aruba", "Access Point"),
    "24:de:c6": ("HPE Aruba", "Switch"),
    "2c:fa:a2": ("HPE Aruba", "Switch"),
    "34:fc:b9": ("HPE Aruba", "Access Point"),
    "40:e3:d6": ("HPE Aruba", "Switch"),
    "48:5b:39": ("HPE Aruba", "Access Point"),
    "4c:e6:76": ("HPE Aruba", "Access Point"),
    "50:3e:aa": ("HPE Aruba", "Access Point"),
    "5c:d2:e4": ("HPE Aruba", "Access Point"),
    "60:67:20": ("HPE Aruba", "Access Point"),
    "64:e8:81": ("HPE Aruba", "Access Point"),
    "68:c9:0b": ("HPE Aruba", "Access Point"),
    "6c:f3:7f": ("HPE Aruba", "Switch"),
    "70:3a:0e": ("HPE Aruba", "Switch"),
    "74:2e:4c": ("HPE Aruba", "Access Point"),
    "78:88:6d": ("HPE Aruba", "Access Point"),
    "80:8d:b7": ("HPE Aruba", "Access Point"),
    "84:d4:7e": ("HPE Aruba", "Switch"),
    "88:5a:06": ("HPE Aruba", "Access Point"),
    "88:f0:31": ("HPE Aruba", "Switch"),
    "8c:a9:82": ("HPE Aruba", "Access Point"),
    "90:2b:34": ("HPE Aruba", "Switch"),
    "90:4c:e5": ("HPE Aruba", "Access Point"),
    "94:b4:0f": ("HPE Aruba", "Access Point"),
    "94:c6:91": ("HPE Aruba", "Switch"),
    "98:de:d0": ("HPE Aruba", "Access Point"),
    "9c:8b:a0": ("HPE Aruba", "Access Point"),
    "a0:1d:48": ("HPE Aruba", "Switch"),
    "a0:a8:cd": ("HPE Aruba", "Access Point"),
    "a4:56:30": ("HPE Aruba", "Access Point"),
    "a8:bd:27": ("HPE Aruba", "Access Point"),
    "ac:a3:1e": ("HPE Aruba", "Switch"),
    "b0:b8:67": ("HPE Aruba", "Access Point"),
    "b4:5d:50": ("HPE Aruba", "Access Point"),
    "b4:fb:e4": ("HPE Aruba", "Switch"),
    "b8:d4:e7": ("HPE Aruba", "Access Point"),
    "bc:9f:e4": ("HPE Aruba", "Access Point"),
    "c0:e4:22": ("HPE Aruba", "Access Point"),
    "c4:01:7c": ("HPE Aruba", "Access Point"),
    "c8:b5:ad": ("HPE Aruba", "Access Point"),
    "cc:d8:c1": ("HPE Aruba", "Access Point"),
    "d0:37:45": ("HPE Aruba", "Access Point"),
    "d4:c1:9e": ("HPE Aruba", "Access Point"),
    "d8:c7:c8": ("HPE Aruba", "Switch"),
    "dc:eb:94": ("HPE Aruba", "Access Point"),
    "e0:1c:41": ("HPE Aruba", "Access Point"),
    "ec:67:94": ("HPE Aruba", "Switch"),
    "f0:5c:19": ("HPE Aruba", "Switch"),
    "f0:92:1c": ("HPE Aruba", "Switch"),

    # ══════════ Konica Minolta ══════════
    "00:20:6b": ("Konica Minolta", "Impressora"),
    "00:26:39": ("Konica Minolta", "Impressora"),
    "00:80:7d": ("Konica Minolta", "Impressora"),
    "00:80:91": ("Konica Minolta", "Impressora"),
    "08:00:43": ("Konica Minolta", "Impressora"),
    "18:ce:1f": ("Konica Minolta", "Impressora"),
    "1c:9e:46": ("Konica Minolta", "Impressora"),
    "28:9d:21": ("Konica Minolta", "Impressora"),
    "2c:49:2e": ("Konica Minolta", "Impressora"),
    "3c:e1:a1": ("Konica Minolta", "Impressora"),
    "44:d2:44": ("Konica Minolta", "Impressora"),
    "54:89:98": ("Konica Minolta", "Impressora"),
    "58:d7:b3": ("Konica Minolta", "Impressora"),
    "5c:8a:38": ("Konica Minolta", "Impressora"),
    "60:eb:69": ("Konica Minolta", "Impressora"),
    "64:99:5d": ("Konica Minolta", "Impressora"),
    "68:b5:99": ("Konica Minolta", "Impressora"),
    "6c:2e:85": ("Konica Minolta", "Impressora"),
    "74:1f:4a": ("Konica Minolta", "Impressora"),
    "78:d3:8d": ("Konica Minolta", "Impressora"),
    "7c:c7:09": ("Konica Minolta", "Impressora"),
    "80:71:7a": ("Konica Minolta", "Impressora"),
    "84:26:15": ("Konica Minolta", "Impressora"),
    "88:c6:63": ("Konica Minolta", "Impressora"),
    "90:1b:0e": ("Konica Minolta", "Impressora"),
    "94:0c:6d": ("Konica Minolta", "Impressora"),
    "98:4b:e1": ("Konica Minolta", "Impressora"),
    "9c:93:4e": ("Konica Minolta", "Impressora"),
    "a0:66:10": ("Konica Minolta", "Impressora"),
    "a4:ba:db": ("Konica Minolta", "Impressora"),
    "a8:1e:84": ("Konica Minolta", "Impressora"),
    "ac:de:48": ("Konica Minolta", "Impressora"),
    "b0:e5:ed": ("Konica Minolta", "Impressora"),
    "b4:7c:9c": ("Konica Minolta", "Impressora"),
    "b8:d9:4e": ("Konica Minolta", "Impressora"),
    "c0:25:e9": ("Konica Minolta", "Impressora"),
    "c4:02:89": ("Konica Minolta", "Impressora"),
    "c8:93:46": ("Konica Minolta", "Impressora"),
    "cc:4b:73": ("Konica Minolta", "Impressora"),
    "d0:27:88": ("Konica Minolta", "Impressora"),
    "d4:6d:50": ("Konica Minolta", "Impressora"),
    "d8:9e:3f": ("Konica Minolta", "Impressora"),
    "dc:ed:84": ("Konica Minolta", "Impressora"),
    "e0:3e:44": ("Konica Minolta", "Impressora"),
    "e4:e7:49": ("Konica Minolta", "Impressora"),
    "e8:b7:48": ("Konica Minolta", "Impressora"),
    "ec:08:6b": ("Konica Minolta", "Impressora"),
    "f0:1f:af": ("Konica Minolta", "Impressora"),
    "f4:81:39": ("Konica Minolta", "Impressora"),
    "f8:bc:12": ("Konica Minolta", "Impressora"),

    # ══════════ Lenovo ══════════
    "00:09:2d": ("Lenovo", "Desktop"),
    "00:22:64": ("Lenovo", "Laptop"),
    "0c:4d:e9": ("Lenovo", "Laptop"),
    "10:65:30": ("Lenovo", "Laptop"),
    "20:89:86": ("Lenovo", "Laptop"),
    "24:4b:fe": ("Lenovo", "Laptop"),
    "38:b1:db": ("Lenovo", "Laptop"),
    "3c:97:0e": ("Lenovo", "Laptop"),
    "40:8d:5c": ("Lenovo", "Laptop"),
    "44:37:19": ("Lenovo", "Laptop"),
    "48:4d:7e": ("Lenovo", "Laptop"),
    "4c:72:b9": ("Lenovo", "Laptop"),
    "50:7b:9d": ("Lenovo", "Laptop"),
    "54:05:db": ("Lenovo", "Laptop"),
    "54:ee:75": ("Lenovo", "Laptop"),
    "58:8f:c6": ("Lenovo", "Laptop"),
    "5c:e0:c5": ("Lenovo", "Laptop"),
    "5c:f3:70": ("Lenovo", "Laptop"),
    "60:02:92": ("Lenovo", "Laptop"),
    "68:f7:28": ("Lenovo", "Laptop"),
    "6c:40:08": ("Lenovo", "Laptop"),
    "6c:88:14": ("Lenovo", "Laptop"),
    "70:5a:b6": ("Lenovo", "Laptop"),
    "70:72:3c": ("Lenovo", "Laptop"),
    "78:2b:cb": ("Lenovo", "Laptop"),
    "7c:7a:91": ("Lenovo", "Laptop"),
    "80:fa:5b": ("Lenovo", "Laptop"),
    "84:34:97": ("Lenovo", "Laptop"),
    "84:7b:eb": ("Lenovo", "Laptop"),
    "88:70:8c": ("Lenovo", "Laptop"),
    "88:dd:e7": ("Lenovo", "Laptop"),
    "8c:8d:28": ("Lenovo", "Laptop"),
    "94:65:2d": ("Lenovo", "Laptop"),
    "98:be:94": ("Lenovo", "Laptop"),
    "98:fa:9b": ("Lenovo", "Laptop"),
    "9c:b6:d0": ("Lenovo", "Laptop"),
    "a4:c3:f0": ("Lenovo", "Laptop"),
    "ac:b5:7d": ("Lenovo", "Laptop"),
    "b0:5a:da": ("Lenovo", "Laptop"),
    "b4:9c:df": ("Lenovo", "Laptop"),
    "b8:ac:6f": ("Lenovo", "Laptop"),
    "c0:b5:d7": ("Lenovo", "Laptop"),
    "c4:69:f0": ("Lenovo", "Laptop"),
    "c4:be:84": ("Lenovo", "Laptop"),
    "d0:53:49": ("Lenovo", "Laptop"),
    "d4:25:8b": ("Lenovo", "Laptop"),
    "d4:f5:47": ("Lenovo", "Laptop"),
    "e0:d5:5e": ("Lenovo", "Laptop"),
    "e4:54:e8": ("Lenovo", "Laptop"),
    "e4:a7:c5": ("Lenovo", "Laptop"),
    "e8:6a:64": ("Lenovo", "Laptop"),
    "f4:a7:33": ("Lenovo", "Laptop"),
    "f8:16:54": ("Lenovo", "Laptop"),
    "fc:f8:ae": ("Lenovo", "Laptop"),

    # ══════════ OKI Data Corp. ══════════
    "00:00:23": ("OKI Data Corp.", "Impressora"),
    "00:20:d8": ("OKI Data Corp.", "Impressora"),
    "00:60:b0": ("OKI Data Corp.", "Impressora"),
    "00:80:92": ("OKI Data Corp.", "Impressora"),
    "18:62:e4": ("OKI Data Corp.", "Impressora"),
    "28:f5:37": ("OKI Data Corp.", "Impressora"),
    "2c:41:38": ("OKI Data Corp.", "Impressora"),
    "40:61:86": ("OKI Data Corp.", "Impressora"),
    "54:10:ec": ("OKI Data Corp.", "Impressora"),
    "5c:f9:dd": ("OKI Data Corp.", "Impressora"),
    "64:3f:5f": ("OKI Data Corp.", "Impressora"),
    "70:8c:b6": ("OKI Data Corp.", "Impressora"),
    "7c:2e:bd": ("OKI Data Corp.", "Impressora"),
    "80:9f:f5": ("OKI Data Corp.", "Impressora"),
    "84:d6:d0": ("OKI Data Corp.", "Impressora"),
    "8c:10:d4": ("OKI Data Corp.", "Impressora"),
    "98:4b:4a": ("OKI Data Corp.", "Impressora"),
    "b0:25:aa": ("OKI Data Corp.", "Impressora"),
    "bc:5f:f4": ("OKI Data Corp.", "Impressora"),
    "d8:f3:bc": ("OKI Data Corp.", "Impressora"),
    "e8:e8:75": ("OKI Data Corp.", "Impressora"),
    "f0:79:59": ("OKI Data Corp.", "Impressora"),

    # ══════════ Ubiquiti Networks ══════════
    "00:15:6d": ("Ubiquiti Networks", "Access Point"),
    "00:27:22": ("Ubiquiti Networks", "Access Point"),
    "04:18:d6": ("Ubiquiti Networks", "Access Point"),
    "0a:18:d6": ("Ubiquiti Networks", "Access Point"),
    "18:e8:29": ("Ubiquiti Networks", "Access Point"),
    "24:5a:4c": ("Ubiquiti Networks", "Access Point"),
    "24:a4:3c": ("Ubiquiti Networks", "Access Point"),
    "28:d2:44": ("Ubiquiti Networks", "Access Point"),
    "44:d9:e7": ("Ubiquiti Networks", "Access Point"),
    "60:22:32": ("Ubiquiti Networks", "Access Point"),
    "68:72:51": ("Ubiquiti Networks", "Access Point"),
    "68:d7:9a": ("Ubiquiti Networks", "Access Point"),
    "70:a7:41": ("Ubiquiti Networks", "Switch"),
    "74:83:c2": ("Ubiquiti Networks", "Access Point"),
    "78:45:58": ("Ubiquiti Networks", "Switch"),
    "78:8a:20": ("Ubiquiti Networks", "Access Point"),
    "80:2a:a8": ("Ubiquiti Networks", "Switch"),
    "c0:4a:00": ("Ubiquiti Networks", "Access Point"),
    "d8:38:fc": ("Ubiquiti Networks", "Access Point"),
    "dc:9f:db": ("Ubiquiti Networks", "Access Point"),
    "e0:63:da": ("Ubiquiti Networks", "Access Point"),
    "f0:9f:c2": ("Ubiquiti Networks", "Access Point"),
    "f4:92:bf": ("Ubiquiti Networks", "Switch"),
    "fc:ec:da": ("Ubiquiti Networks", "Access Point"),

    # ══════════ Zebra Technologies ══════════
    "00:03:ed": ("Zebra Technologies", "Impressora"),
    "00:07:4d": ("Zebra Technologies", "Impressora"),
    "00:0c:39": ("Zebra Technologies", "Impressora"),
    "00:15:70": ("Zebra Technologies", "Impressora"),
    "00:1d:6e": ("Zebra Technologies", "Impressora"),
    "10:f6:0a": ("Zebra Technologies", "Impressora"),
    "14:a2:ef": ("Zebra Technologies", "Impressora"),
    "20:f7:7c": ("Zebra Technologies", "Impressora"),
    "24:62:be": ("Zebra Technologies", "Impressora"),
    "24:f2:7f": ("Zebra Technologies", "Impressora"),
    "28:08:5d": ("Zebra Technologies", "Impressora"),
    "3c:59:1e": ("Zebra Technologies", "Impressora"),
    "40:83:de": ("Zebra Technologies", "Impressora"),
    "48:59:29": ("Zebra Technologies", "Impressora"),
    "4c:bc:a5": ("Zebra Technologies", "Impressora"),
    "50:3d:e5": ("Zebra Technologies", "Impressora"),
    "54:53:ed": ("Zebra Technologies", "Impressora"),
    "5c:09:47": ("Zebra Technologies", "Impressora"),
    "60:c3:97": ("Zebra Technologies", "Impressora"),
    "64:70:33": ("Zebra Technologies", "Impressora"),
    "68:d4:fb": ("Zebra Technologies", "Impressora"),
    "6c:d0:cf": ("Zebra Technologies", "Impressora"),
    "70:38:11": ("Zebra Technologies", "Impressora"),
    "74:c2:46": ("Zebra Technologies", "Impressora"),
    "7c:bc:84": ("Zebra Technologies", "Impressora"),
    "80:0d:60": ("Zebra Technologies", "Impressora"),
    "84:24:8d": ("Zebra Technologies", "Impressora"),
    "88:23:fe": ("Zebra Technologies", "Impressora"),
    "8c:79:f5": ("Zebra Technologies", "Impressora"),
    "90:b8:d0": ("Zebra Technologies", "Impressora"),
    "94:a8:07": ("Zebra Technologies", "Impressora"),
    "98:7b:ca": ("Zebra Technologies", "Impressora"),
    "a0:63:91": ("Zebra Technologies", "Impressora"),
    "a8:41:95": ("Zebra Technologies", "Impressora"),
    "ac:3f:a4": ("Zebra Technologies", "Impressora"),
    "b0:7d:64": ("Zebra Technologies", "Impressora"),
    "b4:a2:eb": ("Zebra Technologies", "Impressora"),
    "b8:cd:b4": ("Zebra Technologies", "Impressora"),
    "bc:76:4e": ("Zebra Technologies", "Impressora"),
    "c0:74:ad": ("Zebra Technologies", "Impressora"),
    "c4:f3:12": ("Zebra Technologies", "Impressora"),
    "c8:db:26": ("Zebra Technologies", "Impressora"),
    "cc:92:e8": ("Zebra Technologies", "Impressora"),
    "d0:e7:82": ("Zebra Technologies", "Impressora"),
    "d4:20:b0": ("Zebra Technologies", "Impressora"),
    "d8:5b:3f": ("Zebra Technologies", "Impressora"),
    "dc:a6:32": ("Zebra Technologies", "Impressora"),
    "e0:2b:e9": ("Zebra Technologies", "Impressora"),
    "e4:aa:5d": ("Zebra Technologies", "Impressora"),
    "e8:e5:d6": ("Zebra Technologies", "Impressora"),
    "ec:f0:fe": ("Zebra Technologies", "Impressora"),

    # ══════════════════════════════════════════════════════════════
    # ADICIONADOS — OUIs reais da rede SML Portugal (auditoria)
    # ══════════════════════════════════════════════════════════════

    # ── Cisco Systems ──
    "00:01:a9": ("Cisco Systems", "Switch"),
    "00:22:ca": ("Cisco Systems", "Switch"),
    "00:45:e2": ("Cisco Systems", "Switch"),
    "1c:0b:8b": ("Cisco Systems", "Switch"),
    "7c:c2:c6": ("Cisco Systems", "Switch"),
    "b0:60:88": ("Cisco Systems", "Switch"),
    "d8:bb:c1": ("Cisco Systems", "Switch"),
    "f8:e4:3b": ("Cisco Systems", "Switch"),

    # ── Dell Inc. ──
    "10:63:c8": ("Dell Inc.", "Desktop"),
    "20:7b:d2": ("Dell Inc.", "Desktop"),
    "38:f3:ab": ("Dell Inc.", "Desktop"),
    "6c:2b:59": ("Dell Inc.", "Desktop"),
    "7c:8a:e1": ("Dell Inc.", "Desktop"),
    "84:ba:59": ("Dell Inc.", "Desktop"),
    "9e:cc:dd": ("Dell Inc.", "Desktop"),
    "a4:4b:d5": ("Dell Inc.", "Desktop"),
    "b4:22:00": ("Dell Inc.", "Desktop"),
    "c8:2a:14": ("Dell Inc.", "Desktop"),
    "c8:7f:54": ("Dell Inc.", "Desktop"),
    "e4:a4:71": ("Dell Inc.", "Desktop"),
    "f4:6b:8c": ("Dell Inc.", "Desktop"),
    "f8:59:71": ("Dell Inc.", "Desktop"),

    # ── HPE Aruba ──
    "00:1b:21": ("HPE Aruba", "Access Point"),
    "00:25:36": ("HPE Aruba", "Access Point"),
    "48:3a:02": ("HPE Aruba", "Switch"),
    "48:9e:bd": ("HPE Aruba", "Access Point"),
    "9c:8c:d8": ("HPE Aruba", "Access Point"),
    "c8:a3:62": ("HPE Aruba", "Access Point"),

    # ── Lenovo ──
    "00:16:25": ("Lenovo", "Laptop"),
    "00:50:aa": ("Lenovo", "Laptop"),
    "00:55:da": ("Lenovo", "Laptop"),
    "00:e0:4c": ("Lenovo", "Laptop"),
    "10:06:ed": ("Lenovo", "Laptop"),
    "18:66:da": ("Lenovo", "Laptop"),
    "28:95:29": ("Lenovo", "Laptop"),
    "30:43:d7": ("Lenovo", "Laptop"),
    "3c:a8:2a": ("Lenovo", "Laptop"),
    "6c:83:75": ("Lenovo", "Laptop"),
    "6c:b3:11": ("Lenovo", "Laptop"),
    "a0:36:bc": ("Lenovo", "Laptop"),
    "a4:1f:72": ("Lenovo", "Laptop"),
    "ac:18:26": ("Lenovo", "Laptop"),
    "c4:c6:e6": ("Lenovo", "Laptop"),
    "f8:fe:5e": ("Lenovo", "Laptop"),

    # ── Microsoft Hyper-V ──
    "00:15:5d": ("Microsoft Hyper-V", "VM"),

    # ── Multicast IPv4 ──
    "01:00:5e": ("Multicast IPv4", "Ignorar"),

    # ── Ubiquiti Networks ──
    "18:c0:4d": ("Ubiquiti Networks", "Switch"),
    "44:5b:ed": ("Ubiquiti Networks", "Switch"),
    "60:95:32": ("Ubiquiti Networks", "Access Point"),
    "74:86:e2": ("Ubiquiti Networks", "Switch"),
    "80:3f:5d": ("Ubiquiti Networks", "Access Point"),
    "f4:39:09": ("Ubiquiti Networks", "Access Point"),
    "f4:4d:30": ("Ubiquiti Networks", "Access Point"),

}


def lookup(mac: str):
    """
    Dado um MAC address em qualquer formato, devolve (fabricante, tipo).
    Devolve (None, None) se não encontrado.
    """
    if not mac:
        return None, None
    normalized = mac.lower().replace("-", ":").replace(".", ":")
    parts = normalized.split(":")
    if len(parts) >= 3:
        oui = ":".join(p.zfill(2) for p in parts[:3])
        result = OUI_DATABASE.get(oui)
        if result:
            return result
    return None, None
